//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.0
//     from Assets/Anna's Testing Scene/GamepadControls/SamuraiControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Anna's Testing Scene/GamepadControls/SamuraiControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @SamuraiControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @SamuraiControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SamuraiControls"",
    ""maps"": [
        {
            ""name"": ""GamepadControls"",
            ""id"": ""533b2ed4-a7fe-4c2e-bcce-8bcb91431d56"",
            ""actions"": [
                {
                    ""name"": ""Dodge Left"",
                    ""type"": ""Button"",
                    ""id"": ""68c0e517-7d2b-462c-84dc-81129503fe15"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slash"",
                    ""type"": ""Button"",
                    ""id"": ""ccd50038-bc9d-4a95-ace1-daa49fe53346"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge Right"",
                    ""type"": ""Button"",
                    ""id"": ""e4d3dd22-f50d-4be3-86a4-1904640ff5da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Clap"",
                    ""type"": ""Button"",
                    ""id"": ""f33e123e-b354-4007-b6e0-7ce86e2ad719"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c3bc377c-9803-4349-a3d3-64d1ae69762c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29919cea-da85-4b59-b237-5fd0bc15411e"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5747f87c-12d2-440c-9b23-9f61740c8973"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d8f1bf1-d0c8-406f-916a-3fc95f248d81"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GamepadControls
        m_GamepadControls = asset.FindActionMap("GamepadControls", throwIfNotFound: true);
        m_GamepadControls_DodgeLeft = m_GamepadControls.FindAction("Dodge Left", throwIfNotFound: true);
        m_GamepadControls_Slash = m_GamepadControls.FindAction("Slash", throwIfNotFound: true);
        m_GamepadControls_DodgeRight = m_GamepadControls.FindAction("Dodge Right", throwIfNotFound: true);
        m_GamepadControls_Clap = m_GamepadControls.FindAction("Clap", throwIfNotFound: true);
    }

    ~@SamuraiControls()
    {
        UnityEngine.Debug.Assert(!m_GamepadControls.enabled, "This will cause a leak and performance issues, SamuraiControls.GamepadControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GamepadControls
    private readonly InputActionMap m_GamepadControls;
    private List<IGamepadControlsActions> m_GamepadControlsActionsCallbackInterfaces = new List<IGamepadControlsActions>();
    private readonly InputAction m_GamepadControls_DodgeLeft;
    private readonly InputAction m_GamepadControls_Slash;
    private readonly InputAction m_GamepadControls_DodgeRight;
    private readonly InputAction m_GamepadControls_Clap;
    /// <summary>
    /// Provides access to input actions defined in input action map "GamepadControls".
    /// </summary>
    public struct GamepadControlsActions
    {
        private @SamuraiControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GamepadControlsActions(@SamuraiControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GamepadControls/DodgeLeft".
        /// </summary>
        public InputAction @DodgeLeft => m_Wrapper.m_GamepadControls_DodgeLeft;
        /// <summary>
        /// Provides access to the underlying input action "GamepadControls/Slash".
        /// </summary>
        public InputAction @Slash => m_Wrapper.m_GamepadControls_Slash;
        /// <summary>
        /// Provides access to the underlying input action "GamepadControls/DodgeRight".
        /// </summary>
        public InputAction @DodgeRight => m_Wrapper.m_GamepadControls_DodgeRight;
        /// <summary>
        /// Provides access to the underlying input action "GamepadControls/Clap".
        /// </summary>
        public InputAction @Clap => m_Wrapper.m_GamepadControls_Clap;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GamepadControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GamepadControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GamepadControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GamepadControlsActions" />
        public void AddCallbacks(IGamepadControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Add(instance);
            @DodgeLeft.started += instance.OnDodgeLeft;
            @DodgeLeft.performed += instance.OnDodgeLeft;
            @DodgeLeft.canceled += instance.OnDodgeLeft;
            @Slash.started += instance.OnSlash;
            @Slash.performed += instance.OnSlash;
            @Slash.canceled += instance.OnSlash;
            @DodgeRight.started += instance.OnDodgeRight;
            @DodgeRight.performed += instance.OnDodgeRight;
            @DodgeRight.canceled += instance.OnDodgeRight;
            @Clap.started += instance.OnClap;
            @Clap.performed += instance.OnClap;
            @Clap.canceled += instance.OnClap;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GamepadControlsActions" />
        private void UnregisterCallbacks(IGamepadControlsActions instance)
        {
            @DodgeLeft.started -= instance.OnDodgeLeft;
            @DodgeLeft.performed -= instance.OnDodgeLeft;
            @DodgeLeft.canceled -= instance.OnDodgeLeft;
            @Slash.started -= instance.OnSlash;
            @Slash.performed -= instance.OnSlash;
            @Slash.canceled -= instance.OnSlash;
            @DodgeRight.started -= instance.OnDodgeRight;
            @DodgeRight.performed -= instance.OnDodgeRight;
            @DodgeRight.canceled -= instance.OnDodgeRight;
            @Clap.started -= instance.OnClap;
            @Clap.performed -= instance.OnClap;
            @Clap.canceled -= instance.OnClap;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GamepadControlsActions.UnregisterCallbacks(IGamepadControlsActions)" />.
        /// </summary>
        /// <seealso cref="GamepadControlsActions.UnregisterCallbacks(IGamepadControlsActions)" />
        public void RemoveCallbacks(IGamepadControlsActions instance)
        {
            if (m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GamepadControlsActions.AddCallbacks(IGamepadControlsActions)" />
        /// <seealso cref="GamepadControlsActions.RemoveCallbacks(IGamepadControlsActions)" />
        /// <seealso cref="GamepadControlsActions.UnregisterCallbacks(IGamepadControlsActions)" />
        public void SetCallbacks(IGamepadControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_GamepadControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GamepadControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GamepadControlsActions" /> instance referencing this action map.
    /// </summary>
    public GamepadControlsActions @GamepadControls => new GamepadControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GamepadControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GamepadControlsActions.AddCallbacks(IGamepadControlsActions)" />
    /// <seealso cref="GamepadControlsActions.RemoveCallbacks(IGamepadControlsActions)" />
    public interface IGamepadControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Dodge Left" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDodgeLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Slash" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSlash(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Dodge Right" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDodgeRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Clap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnClap(InputAction.CallbackContext context);
    }
}
